blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://ideas.obsproject.com
    about: Ideas for new features and functionality
  - name: Help/Support
    url: https://obsproject.com/help
    about: Links to support avenues, including Forums nad Discord
